// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV5C1spaS7ZLSrTTSIXatdeVawzcc3TBM',
    appId: '1:584836607847:web:9a00ed50dda19dea3d49c2',
    messagingSenderId: '584836607847',
    projectId: 'chat-app-f347e',
    authDomain: 'chat-app-f347e.firebaseapp.com',
    storageBucket: 'chat-app-f347e.appspot.com',
    measurementId: 'G-GE9HZGMKNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcE4yEatdt9AnqgPbdLUfYDSzVZ4iluR8',
    appId: '1:584836607847:android:47356394bbb85c7f3d49c2',
    messagingSenderId: '584836607847',
    projectId: 'chat-app-f347e',
    storageBucket: 'chat-app-f347e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa2AIS7wJkn7nehtf-djA6JFwQfNnhltY',
    appId: '1:584836607847:ios:58405b01a591e5413d49c2',
    messagingSenderId: '584836607847',
    projectId: 'chat-app-f347e',
    storageBucket: 'chat-app-f347e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa2AIS7wJkn7nehtf-djA6JFwQfNnhltY',
    appId: '1:584836607847:ios:58405b01a591e5413d49c2',
    messagingSenderId: '584836607847',
    projectId: 'chat-app-f347e',
    storageBucket: 'chat-app-f347e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
